### ISSUE TITLE
New member 26 Spoonerisms

### ISSUE THREAD

**Issue by webtechalex** [codingforeveryone/js#104]
A spoonerism is a spoken phrase in which the first letters of two of the words are swapped around, often with amusing results.

This issue is taken from my very first [Codewars Kata](http://www.codewars.com/kata/56b8903933dbe5831e000c76)

In its most basic form a spoonerism is a two word phrase in which only the first letters of each word are swapped:

```javascript
"not picking" --> "pot nicking"
```

Your task is to create a function that takes a string of only two words, separated by a space and returns a spoonerism of those words in a string, as in the above example.

NOTE: Spoonerisms can be more complex. For example, three-word phrases in which the first letters of the first and last words are swapped: ```"pack of lies" --> "lack of pies"``` or more than one letter from a word is swapped: ```"flat battery --> "bat flattery"``` You are NOT expected to account for these, or any other linguistic nuances involved in spoonerisms.

**Comment by Janechester** [comment]
Hey Alex,

Had an attempt at this one but got a little stuck when it came to removing the first letter from the original string. 

`function spoon1(word1, word2){
return word1.slice(0,1) + word2 +  word2.slice(0,1) + word1;
}`

which would return:
`spoon("Jane", "Chester");
"JChester CJane"`

Not quite ideal! 

Let me know what your suggestions might be on how to fix this one up...

**Comment by webtechalex** [comment]
Great start, Jane.  You are very close.  To give you a clue, don't think of it so much as "removing" the letters from the strings as returning an "added up" string.
By the way, if you want to solve the Codewars kata as well you're going to have to come up with a version that takes a single string: ```"Jane Chester"``` rather than two separate ones :)  My apologies, I should have made that explicit in the description, keep working on the two-argument solution for now though.  :)

**Comment by Janechester** [comment]
Thank you for the that hint Alex!

Bingo.

`function spoon(word1, word2){`
`return word2[0] + word1.slice(1) + " " + word1[0] + word2.slice(1);`
`}`

**Comment by webtechalex** [comment]
Thanks Jane.  Well done!  Now try the Codewars version  ;) (link in original post)
