### ISSUE TITLE
new-member-33: Amount to coins

### ISSUE THREAD

**Issue by juliankolbe** [codingforeveryone/js#116]
## Amount to Coins

Write a function that converts a given amount to change in the levels of Euro.

#### Input will be: 
* an integer with the amount e.g. `60`
* an array with the Euro levels: `[1000,500,200,100,50,20,10,5,2,1]`

#### Output should be:
* an object containing the number of levels used for each level, including those that were not used.
* example for `60`: `{1000: 0, 500: 0, 200: 0, 100: 0, 50: 1, 20: 0, 10: 1, 5: 0, 2: 0, 1: 0}`
* example for `576`: `{1000: 0, 500: 1, 200: 0, 100: 0, 50: 1, 20: 1, 10: 0, 5: 1, 2: 0, 1: 1}`

Always make sure to use the highest bills possible.

This is a simplified version of [my kata on Codewars](http://www.codewars.com/kata/574f19f114b9ad878600178a). If you have passed this exercise feel free to give it a go ;).

**Comment by stevehopkinson** [comment]
Hi Julian - I'll pick this one up. Ta!

**Comment by juliankolbe** [comment]
Hi Steve, well done! Took a while for someone to have a go at it :P, Cheers!
