### ISSUE TITLE
new-member-36: Uncamcelcase

### ISSUE THREAD

**Issue by majakudlicka** [codingforeveryone/js#122]
<h3>Problem Specification</h3>

Write a function Uncamelcase(str) that takes as an input a string (sentence) written in camelCase and turns it into a grammatically correct sentence.

<h4>Input:</h4>

- String (sentence) written in camelCase  eg. "learningHowToCodeIsFun"

<h4>Output:</h4>

- String - grammatically correct sentence (beginning with capital letter and ending with a dot) eg. "Learning how to code is fun."

<h4>Example:</h4>

Uncamelcase('learningHowToCodeIsFun') --> 'Learning how to code is fun.'

**Comment by JWLD** [comment]
I'll give this one a go :)

**Comment by majakudlicka** [comment]
Nice and clever solution to the problem. Congrats!
