### ISSUE TITLE
Idea for beginners

### ISSUE THREAD

**Issue by JMurphyWeb** [codingforeveryone/js#23]
I have an idea which is designed to assign anyone new to this repository a problem that they can then practice using the guide set out by @patrickwalkowicz  in the README.

* Each new member of the repo will always find an easy problem waiting for them.
* Once they have reserved and then solved the problem, they must create a new easy problem, designated for the next new member to the repo.
* To distinguish the "New Member" problem, it should be named new-member-1, new-member-2 ...

 This way there is always a simple JS problem to solve for any new member to this repository.  Let me know your thoughts.

**Comment by Bektaz** [comment]
Hi @JMurphyWeb,

As I understood there are would be two activities going parallely about creating and solving problem. One is as described in README.md which is for existing contributors and the other one for new members. New members will solve tasks named with 'new' whereas existing members will solve nonnew tasks and they dont touch each other's tasks. Did I understand in correct way?

**Comment by patrickwalkowicz** [comment]
@JMurphyWeb it makes perfect sense to do that this way. If I understand correctly, you mean creating very basic JS problems for somebody who's learning from the very beginning so the person won't have to wrestle with the problem itself and still learn about GitHub?

From the beginning when we started participating in this repo I was thinking about ways how we can make this repo more about GitHub than JS. As you've mentioned, there's a lot of problems of various difficulty on Codewars so I think we should find ways to make the experience different as opposed to trying to emulate Codewars the way it is. And I think that stressing the GitHub learning part of this repo is the way to do that.

**Comment by JMurphyWeb** [comment]
@Bektaz   Yes I think you have the understood as I intended.  @patrickwalkowicz Yes that is the idea, but it is important that each new member to the repo creates another "new-member-x+1" problem for the next new member to arrive here.  Creating a cycle of easy problems for new members.

The README should be updated so that the first thing it says is along these lines: 

##New Members
* If you are a new member to this repository, you should find the issue called "new-member-x"
* solve this problem (an explanation or a link explaining how to make a branch could be inserted here)
* create a pull request for your solution (explanation needed?)
* Create a new issue with an adequately simple JS problem titled "new-member-x+1" for the next new member to practice with.

**Comment by Bektaz** [comment]
This would be good point for new members to start once they are in this repo. Also new members would get their first or beginner experiences in creating branch repo, pushing, pulling requests and opening issues. I am for it. If you open pull request and add your changes then all of us could look and comment if we have one of course, otherwise you could merge it.

**Comment by toast565** [comment]
Hey all, thought I'd weigh in as a prospective new member. I really like the idea, really welcoming and encouraging people to get involved (and making sure existing members don't solve all the problems too fast!)

One suggestion: consider maybe keeping two 'new-member' problems open at once; that way a new member has some time to come up with a new problem after they've solved the old one, but if another new member comes along, there's still a second 'new-member' problem waiting in reserve for them..

Lemme know if that makes sense.

**Comment by JMurphyWeb** [comment]
@toast565, makes sense indeed. Could you please create a new-member-1 issue with a simple JS problem to be solved, since you were the latest member to solve a problem? 

I think as we discussed earlier we should all try to add one or two general problems of our own to ensure there are many questions to be solved.  If we solve someones problem, then maybe we should add another of our own?

**Comment by toast565** [comment]
Yep. Sorry for the delay - I've uploaded a new member problem. It was hard to gauge what the difficulty should be but I think that with the help of Google this one shouldn't be particularly hard.

**Comment by Katbow** [comment]
Seeing as this is more or less done now, this issue can now be closed.
