### ISSUE TITLE
Project Euler 1

### ISSUE THREAD

**Issue by JMurphyWeb** [codingforeveryone/js#24]
Slightly adapted the first problem from project euler:
https://projecteuler.net/problem=1

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

**Create a function that will find the sum of all the multiples of 3 or 5 below an integer x**

function sumOfMultiples(x){
//
}

**Comment by toast565** [comment]
Hey I think I managed to make my first pull request with a solution to this. Have a look? :)
