### ISSUE TITLE
New Member #1 - sumCircles

### ISSUE THREAD

**Issue by toast565** [codingforeveryone/js#30]
Write a function that takes as its parameters *some numbers representing the diameters of circles*.

It should return the *sum of the areas of all these circles*, rounded to the nearest integer, as a string: "We have this much circle: xyz".

You don't know how many circles there will be, but you can assume there will be at least one. 

function sumCircles(){
  // codecodecode
}

sumCircles(2) // returns "We have this much circle: 3"
sumCircles(2, 3, 4)// returns "We have this much circle: 23"

**Comment by thankgodr** [comment]
I have created a function that solve this issue. I will be pushing and will create a pull request.

**Comment by thankgodr** [comment]
Please i am new to git. What branch should i push the js file to?

**Comment by patrickwalkowicz** [comment]
Hello @thankgodr! Please push your solution to a newly created "sumCircle" branch. Then create a pull request from sumCircle to master.

For reference, I've created an outline:
(using command line)
1. Navigate to a folder you want to use for the project, use `git clone https://github.com/codingforeveryone/js.git` to clone the repository
2. Create a new branch  *locally* using `git checkout -b sumCircles` (using -b flag you'll switch to newly created branch).
3. Create new folder for the problem `*your_project_directory*/sumCircles` and place sumCircles.js with the solution in it.
4. When the file is ready, add it to git `git add *`. Then run `git status` to check if the file is added (should be marked green).
5. Commit changes locally `git commit -m "your message"` (anything you want, eg. "sumCircle solution")
6. Push changes to sumCircle branch in remote repository `git push origin sumCircle`
