### ISSUE TITLE
New member in need of a problem

### ISSUE THREAD

**Issue by tas12** [codingforeveryone/js#41]

**Comment by hatsot** [comment]
me too, i need some problems in my life :D

**Comment by Katbow** [comment]
@franzmoro is busy adding a new problem in PR #43. I may also add a new problem soon to get things moving again and I'll ping you when it's done.

**Comment by franzmoro** [comment]
I've added problem number 5 (pull request #43 and issue #44 ). I have also created another codewars [kata] (http://www.codewars.com/kata/565b3542af398bfb50000003), which is more beginner-friendly than the Article archive problem. If as per issue-title, there is need of more problems, I can add it as problem #6. :wink:

**Comment by Katbow** [comment]
closing issue as new problem has been submitted/completed. @hatsot if you are still in need of a problem, please post a new issue or reopen this one.
