### ISSUE TITLE
New member #6 - Count strings inside an object

### ISSUE THREAD

**Issue by franzmoro** [codingforeveryone/js#47]
Create a function strCount (takes an object as argument) that will count all string values inside an object. For example:

```javascript
strCount({
  first: "1",
  second: "2",
  third: false,
  fourth: ["anytime",2,3,4]
  fifth:  null
  })
  //returns 3
```

**Comment by philb56** [comment]
I'd like to have a go at this - first time so very unclear about the process.

**Comment by franzmoro** [comment]
@philb56 has provided a working solution, which is now in the repo. Closing issue.
