### ISSUE TITLE
Problems to solve #1 Simple Events

### ISSUE THREAD

**Issue by andrewMacmurray** [codingforeveryone/js#48]
Hi Everyone, have created a new branch with a problem I'm stuck on on codewars - it's this one if you want to have a look http://www.codewars.com/kata/52d3b68215be7c2d5300022f

Has anyone completed it yet? It's a nice OOP one about constructing an object that handles an events but can't get my head around what I'm doing wrong!

**Comment by Katbow** [comment]
@andrewMacmurray I haven't done this one yet, but I will have a go. Then maybe tomorrow we can try it out together at the meet up.

**Comment by andrewMacmurray** [comment]
@Katbow Brilliant, let's solve it tomorrow!

**Comment by Katbow** [comment]
Feels good closing this issue @andrewMacmurray !

**Comment by andrewMacmurray** [comment]
@Katbow Definitely!
