### ISSUE TITLE
Can I please become new-member-#7? 

### ISSUE THREAD

**Issue by tu6619** [codingforeveryone/js#50]
If not, which new-member-# can I be?

**Comment by Katbow** [comment]
@tu6619 , @philb56 should be posting a new issue soon. Then you just need to comment on it that you intend to solve the problem.

**Comment by philb56** [comment]
@tu6619  @Katbow I'll do this today - I'll let you know when it's ready

**Comment by tu6619** [comment]
@Katbow @philb56  cheers guys!

**Comment by Katbow** [comment]
Closing as @philb56 posted the problem & @tu6619 completed it.
