### ISSUE TITLE
New-Member-#7

### ISSUE THREAD

**Issue by philb56** [codingforeveryone/js#51]
Function nthChar takes 1 parameter - an array of n words.

You must concatenate the nth letter from each word to construct a new word which should returned as a string.

Note: Test cases contain valid input only - i.e. a string array or an empty array.

function nthChar(words){
 ...
}

so nthChar(['yxx','xex','xxs']) should return 'yes'

This is one of my katas on Codewars called Substring Fun if you want to practice:

http://www.codewars.com/kata/565b112d09c1adfdd500019c

**Comment by tu6619** [comment]
I'll have a crack at this one.

**Comment by Katbow** [comment]
Closing - solved & solution merged by @tu6619
