### ISSUE TITLE
New-Member-#8

### ISSUE THREAD

**Issue by tu6619** [codingforeveryone/js#53]
Write a function that removes all the even characters from a string and returns them in an array. If the string is smaller than two characters and longer than 100 characters, the function should return "invalid string". 

For example:
`````
function evenChars("abcdefghijklm") {}
// should return ["b", "d", "f", "h", "j", "l"]

function evenChars("a")
// should return "invalid string"
`````

I've posted this problem as a [Codewars Kata](http://www.codewars.com/kata/return-a-strings-even-characters/train) if you want to practice!

**Comment by kylebuttner** [comment]
I'll take this one!

**Comment by shouston3** [comment]
Nice idea for the kata @tu6619, also like this page, very easy to use

**Comment by JackTierney** [comment]
Great kata @tu6619 decent layout

**Comment by RobStallion** [comment]
Nice kata @tu6619. Enjoyed doing that

**Comment by andrewMacmurray** [comment]
Good job everyone, great to see this repo being used. Feel free to suggest changes to the repo too if you've got any ideas

**Comment by Katbow** [comment]
@kylebuttner , do you have the completed solution for this to make a pull request so this issue can be closed? Thanks!
