### ISSUE TITLE
Additions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Katbow** [codingforeveryone/js#58]
These are suggestions for improvements and clarifications to CONTRIBUTING.md. 

Suggestion by @tas12 - For step 1: I think when a new member needs to open an issue to request a problem you could include that bit about what they should name the issue (before it was "New member in need of a problem"). Then it's easier to identify issues that are new problem requests.

Suggestion by @andrewMacmurray - Maybe add something here like "Join our chat room on gitter, we'd love to hear from you!", just to make it very clear this is a friendly and sociable repo. This could also go at the top of the README.md by the gitter channel button!

Suggestion by @tu6619 - What about adding something to the line "Keep the problem simple!"? Maybe something like "Have a look at 8kyu and 7kyu Katas on Codewars for inspiration!".

**Comment by Katbow** [comment]
I added the second suggestion in to README.md - there was something like this already in CONTRIBUTING.md, but if anyone wants to reword that part, feel free.

First and last suggestion are still open if someone would like to add!

**Comment by tas12** [comment]
I've added the first suggestion to both README.md and CONTRIBUTING.md

**Comment by Katbow** [comment]
Thanks for adding that in @tas12 ! I think though that it might be better suited to just the contributing guide. It's a bit of 'additional info' that's not essential when going through the steps. I think it would be good to keep the readme as short and concise as possible. Thoughts?

**Comment by tas12** [comment]
Hey @Katbow I did consider that but I thought some people might not look at the contributing guide, open a new issue and give it their own title. It wouldn't be a big deal but would defeat the purpose of having a specific name for it. What do you think?

**Comment by tas12** [comment]
@Katbow okay, I've just reworded point 1 of the READ.ME. It says they same thing but it's shorter now

**Comment by tas12** [comment]
@Katbow Have made point 1 of the contributing guide match the READ.ME as I think the new wording is better. Let me know if you have any suggestions about this

**Comment by andrewMacmurray** [comment]
@tas12 I think because the repo is just about getting comfortable with github the naming isn't super important, as long as there are open issues then it should be fine. Also we should submit changes via pull requests so we can review them rather than just merging automatically.

**Comment by Katbow** [comment]
Closing as all additions have been made.
