### ISSUE TITLE
New member in need of a problem

### ISSUE THREAD

**Issue by tdowek1** [codingforeveryone/js#66]
Hi guys!

A new issue would be greatly appreciated, as I am new to the group.

Cheers!

**Comment by gabrielperales** [comment]
Hi, @tdowek1 I have solved 5 and 11, but I didn't merge them. If you want you can solve one of them (I'm going to merge only one), or you can wait until I create a new issue.

**Comment by gabrielperales** [comment]
I'm new too... and I didn't know If somebody has to merge it... and until I have waiting I have solved a lot of issues... sorry!

Welcome to the group, and I hope I can help you need it. :)

**Comment by tdowek1** [comment]
Hi Gabriel,

Thank you! I appreciate it!  

I'll take on number 11 if that's alright?

**Comment by gabrielperales** [comment]
Ok,  I'll be waiting to see your solution :)
