### ISSUE TITLE
New-member-14 remove noise from the message

### ISSUE THREAD

**Issue by gabrielperales** [codingforeveryone/js#72]
We have a broken message machine that introduces noise to our incoming messages. We know that our messages are written using `a-zA-Z` and white characters (like spaces or tabs). Unfortunately our machine introduces noise, which means that our message arrives with characters like: `%$&/#·@|º\ª` within our original message.

Your mission is to write a function which removes this noise from the message, but there is bad news, the computer designated to host our program has some limitations and we can't use loops in our scripts (that is, we can't use `for`, `while` and `forEach` loops), instead, we should use regular expressions, `map`, `reduce` or/and `replace`.

Example:
```javascript
removeNoise("h%e&·%$·llo w&%or&$l·$%d")
// returns hello world

removeNoise("he%$·ll@o c$&%odi%&ng for ev|#·ery&$$#$on%$·e")
// returns hello conding for everyone
```

**Comment by comountainclimber** [comment]
solved... have no idea what I am doing as far as merging/branching but I can post a new problem if someone clearly explains how

**Comment by gabrielperales** [comment]
Your solution is right, that's the way you should to use regular expressions :+1:.
You have create a new Issue to create your own problem.

**Comment by comountainclimber** [comment]
Nice thank you... I posted a new problem to be solved in issues. Thanks gabriel!

**Comment by gabrielperales** [comment]
I have seen it :). For questions that you could have, we have this [gitter](https://gitter.im/codingforeveryone/js), there you can ask what you want.

**Comment by katbow** [comment]
Closing issue as it has now been merged.
