### ISSUE TITLE
We Have Liftoff!

### ISSUE THREAD

**Issue by comountainclimber** [codingforeveryone/js#77]
You have an array of numbers 1 through 10 (JS: 1 through 10 or less). The array needs to be formatted correctly for the person reading the countdown of a spaceship launch.

Unfortunately, the person reading the countdown only knows how to read strings. After the array is sorted correctly make sure it's in a format he can understand.

Between each number should be a space and after the final number (1) should be the word 'liftoff!'

Example:
[8,1,10,2,7,9,6,3,4,5]
Should return
"10 9 8 7 6 5 4 3 2 1 liftoff!"

[1,2,4,3,5]
Should return
"5 4 3 2 1 liftoff!"

**Note I am not the original author of this exercise http://www.codewars.com/users/SpencerCDixon

**Comment by mcelearr** [comment]
Thanks for the challenge @comountainclimber. I'd like to try solving this one!

**Comment by mcelearr** [comment]
I completed the kata but don't have permission yet to push my branch (only completed appllication part 1 the other day) so I'll have to wait until then!
