### ISSUE TITLE
Tube strike options calculator

### ISSUE THREAD

**Issue by mcelearr** [codingforeveryone/js#79]
<h1>Tube strike options calculator</h1>
<h3>The sweaty bus ride</h3>
There is a tube strike today so instead of getting the London Underground home you have decided to take the bus. It's a hot day and you have been sitting on the bus for over an hour, but the bus is hardly moving. Your arm is sticking to the window and sweat drips off your nose as you try to read your neighbour's book when you say to yourself, "This is ridiculous. I could have walked faster than this!" Suddenly you have an idea for an app that helps people decide whether to walk or take the bus home when the London Underground is on strike.

You rush home (relatively speaking) and begin to define the function that will underpin your app.

<h3>Function specification</h3>
You must create a function which takes three parameters; walking distance home, distance the bus must travel, and the combined distance of walking from the office to the bus stop and from the bus stop to your house. All distances are in kilometres.

So for example, if your home is 5km away by foot, and the bus that takes you home travels 6km, but you have to walk 500 metres to the bus stop to catch it and 500 metres to your house once the bus arrives (i.e. 1km in total), which is faster, walking or taking the bus?

Walking speed and bus driving speed have been given to you as two pre-loaded constants.

```walk``` = 5 (km/hr)
```bus``` = 8 (km/hr)

The function must return the fastest option, either "Walk" or "Bus". If the walk is going to be over 2 hours, the function should recommend that you take the bus. If the walk is going to be under 10 minutes, the function should recommend that you walk.

http://www.codewars.com/kata/tube-strike-options-calculator/javascript

**Comment by dumbdev** [comment]
Thanks for the kata. The correct link is:
http://www.codewars.com/kata/tube-strike-options-calculator/javascript

Kind Regards,
Ed.

**Comment by matthewglover** [comment]
Hi nice @mcelearr - I'd like to take this one. Just solved it on Codewars, so now have to work out how to do a pull request...
