### ISSUE TITLE
Write function revertString

### ISSUE THREAD

**Issue by patrickwalkowicz** [codingforeveryone/js#8]
# Revert String

I've got a string manipulation problem to solve for you.

Write a function that will revert a word but preserve the original lowercase/uppercase letter order. It's easiest to explain with examples:
- If you pass "JavaScript", the function should return "TpirCsavaj"
- If you pass "RaNdom", the function should return "MoDnar"
As you can see looking at the output, the string itself is reverted *but* the order of capital letters is preserved - just the same as in the input string (in "RaNdom" the first and third letter is capital in both input and output).

# Input restrictions:
- You can assume that only one word will be passed as input
- Input of type string, only alphabetical characters

My idea is to start with simple one-word input and improve as we go - eventually getting to multiple words and characters other than alphabetical.

**Comment by daymos** [comment]
pushed, should work
