### ISSUE TITLE
New member needs an issue..

### ISSUE THREAD

**Issue by coudrew** [codingforeveryone/js#84]
Hey all,

I'm in need of an issue to take on here.

Thanks

**Comment by gabrielperales** [comment]
Hey @coudrew , I just have created #85. I'm not a native english speaker... so, let me know If there is something that you can't understand, and I'll try to explain it again. Good luck :)

**Comment by coudrew** [comment]
@gabrielperales awesome, thanks! :)

**Comment by gabrielperales** [comment]
@coudrew Another thing, send me a message through [gitter](https://gitter.im/codingforeveryone/js) If you need some help.
