### ISSUE TITLE
New-member-16 Multi-criteria filter

### ISSUE THREAD

**Issue by gabrielperales** [codingforeveryone/js#85]
### You must to choose one:
- **Approach one** (the easy one):
Write a function called `multiFilter` which receives two arrays as parameters. The first one is the collection to be filtered and the second one is an array of `functions`.  The function should return all elements which pass all filter functions.

That is, if we have two functions:

```javascript
function isEven(el){
  return el % 2 === 0;
}
```

and 

```javascript
function isGTten(el){
  return el > 10;
}
```

then

```javascript
multiFilter([1,2,3,4,10,11,12,20,21,22], [isEven, isGTten]) // returns [12,20,22]
```

- **Approach two**:
Write a function called `multiFilter` which receives one array of  filter `functions`.  The function should return a function that receives one element (a compound filter function).

That is, if we have two functions:

```javascript
function isEven(el){
  return el % 2 === 0;
}
```

and 

```javascript
function isGTten(el){
  return el > 10;
}
```

then

```javascript
[1,2,3,4,10,11,12,20,21,22].filter(multiFilter([isEven, isGTten])) // returns [12,20,22]
```

**Comment by coudrew** [comment]
@gabrielperales Ok. Solved, pushed, and merged (I hope it wasn't bad form to merge it on my own, but I wanted to see if it was just as easy as clicking a button). I went with approach #1.

**Comment by gabrielperales** [comment]
hahaha, I think you should have made a pull request and wait until somebody merge it, but I hope It doesn't matter. Your solution looks good. I'll post what I had done (my solution) if I had to do it :)
