### ISSUE TITLE
New member 18 Quartile Methods

### ISSUE THREAD

**Issue by mcelearr** [codingforeveryone/js#89]
Create a new object called `Stats` that has three methods:

<ul>
<li>Stats.median</li>
<li>Stats.lowerQuartile</li>
<li>Stats.upperQuartile</li>
</ul>

`median` should return the number at the midpoint in a sorted array. `lowerQuartile` should return the number one quarter of the way through the array. `upperQuartile` should return the number three quarters of the way through the array. When a cut-off point is between two numbers, take the average of the numbers on either side. Round your answer to a maximum of two decimal places.

All inputs will be valid arrays of numbers.

Here is the kata on codewars http://www.codewars.com/kata/quartile-methods

**Comment by RichAWarren** [comment]
Ill take this one!
