### ISSUE TITLE
new-member-23 move Vowels

### ISSUE THREAD

**Issue by davidnge** [codingforeveryone/js#97]
Given a string as input, move all of its vowel to the end of the string.

Example input: day
Example output: dya

Example input: apple
Example output: pplae

Note: All input string are of small capital letters, and the order of the vowels at the end should be the same as they were before.

Here's the link to the kata on codewars: http://www.codewars.com/kata/56bf3287b5106eb10f000899

**Comment by TroyMaeder** [comment]
That looks like fun! I'll take that one thanks David!
